print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")
print("alkjflksjafojasofjiowjeokwej")